apiVersion: v1
kind: Service
metadata:
  name: box-service
  namespace: kubespace
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
    nodePort: 32100
  selector:
    app: box